### ISSUE TITLE
input is not working : email box

### ISSUE THREAD

**Issue by AbhishekLwagun** [KrystalJean/ABC-Coaching-template#7]

**Comment by KrystalJean** [comment]
@AbhishekLwagun We definitely need this enhancement. I will assign you to this issue. Also, would you be able to add an error message if it is not in proper email format when you click submit?

**Comment by AbhishekLwagun** [comment]
@KrystalJean   I  have fixed the input issue and email format on click submit .

**Comment by KrystalJean** [comment]
@AbhishekLwagun Thank you. This looks great! I did not expect to see the input come up in a new box like that. Great Work!
Happy Hacktoberfest!  

Merged with Issue #8

**Comment by AbhishekLwagun** [comment]
@KrystalJean  I'm glad to know that you like it.
